import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styles1 from '../styles/ind.module.css'
import Link from 'next/link'



export default function Home({Newproid}) {
 
 
  return (


    <div>

      <Head>

        <title>hunting  coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        
      </Head>


      <h1>Welcome to my website!</h1>
      <p>This is the home page.</p>
   

    
    </div>


      
)
}


 



